### ISSUE TITLE
Tornado extension should use path args, not method args

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/apispec-webframeworks#12] opened 2018-11-03 14:29 UTC
<a href="https://github.com/zdexter"><img src="https://avatars3.githubusercontent.com/u/588935?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zdexter](https://github.com/zdexter)**
_Sunday Oct 08, 2017 at 22:45 GMT_
_Originally opened as https://github.com/marshmallow-code/apispec/issues/159_

----

Currently using webargs with `marshmallow` breaks the tornado extension in `apispec`:

```
from webargs.tornadoparser import use_kwargs

class MyHandler(RequestHandler):

    @use_kwargs(SomeMarshmallowSchema())
    def get(self, arg):
```

The error is:
```
File "spec.py", line 34, in get
spec.add_path(urlspec=urlspec)
File "/usr/local/lib/python3.6/dist-packages/apispec/core.py", line 191, in add_path
raise APISpecError('Path template is not specified')
```

that's because `tornadopath2swagger` gets the method arguments at the python level:

```
    if sys.version_info >= (3, 3):
        args = list(inspect.signature(method).parameters.keys())[1:]
    else:
        if getattr(method, '__tornado_coroutine__', False):
            method = method.__wrapped__
        args = inspect.getargspec(method).args[1:]
    params = tuple('{{{}}}'.format(arg) for arg in args)
```

ideally `tornadopath2swagger` can call `path_args` and `path_kwargs` on the `RequestHandler` instance (if possible) or otherwise get the path args/kwargs from tornado.

**Comment by lafrech** [comment] 2018-11-03 14:29
<a href="https://github.com/danigosa"><img src="https://avatars3.githubusercontent.com/u/1827475?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [danigosa](https://github.com/danigosa)**
_Sunday Oct 22, 2017 at 10:29 GMT_

----

We also found this bug annoying, it makes impossible to use `webargs` decorators inline with `apispec`, which is too verbose (using the parser directly inside the method).

**Comment by lafrech** [comment] 2018-11-03 14:29
<a href="https://github.com/yoichi"><img src="https://avatars1.githubusercontent.com/u/107537?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [yoichi](https://github.com/yoichi)**
_Sunday Oct 22, 2017 at 14:14 GMT_

----

I do not use tornado and I have no idea how to fix it, but I found the conditional branch was introduced in https://github.com/marshmallow-code/apispec/pull/103.
Do you have an idea how to deal with it? @matijabesednik

**Comment by lafrech** [comment] 2018-11-03 14:29
<a href="https://github.com/sloria"><img src="https://avatars2.githubusercontent.com/u/2379650?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sloria](https://github.com/sloria)**
_Sunday Oct 29, 2017 at 01:33 GMT_

----

@zdexter @danigosa I would certainly review and merge a PR fixing this.

**Comment by nicholasamorim** [comment] 2019-03-05 09:41
I've been trying to fix this but I'm unsure how.

An easy (and wrong) fix is to simply 

```python
if '%s' not in path_tpl:
            return path_tpl
            
        path = (path_tpl % params)
        if path.count('/') > 1:
            path = path.rstrip('/?*')
        return path
```

The problem, of course, is that this will hide real errors. When we do something like this:

```
@use_kwargs(CheckParameters(strict=True))
    def post(self, param1, param2):
```

The code assumes then that `param1` and `param2` _must be_ in the `URLSpec` - which is _not true_. We add it just so `use_kwargs` can do its job.

Ideally (I think?) we'd be able to detect the decorator usage and in such cases, let it slip.

We can't use `path_args` or `path_kwargs` because at this stage, no request exists. It happens at APISpec instantiation.

Pointers on how to fix this?

**Comment by nicholasamorim** [comment] 2019-04-11 08:32
Hey guys, any pointers here?

**Comment by sloria** [comment] 2019-04-11 13:09
Unfortunately, I can't look into this issue right now, as I'm not using the Tornado extension. I'm still open to reviewing/merging a fix, but I don't have time to do a code dive.

**Comment by elfjes** [comment] 2019-11-19 19:30
@nicholasamorim Is this still an issue for you in 0.5.1? It should be fixed in #62

**Comment by elfjes** [comment] 2019-12-08 12:40
Closing this as fixed

**Closed by elfjes** 2019-12-08 12:40 UTC
Labels: bug, help wanted, tornado

**Comment by nicholasamorim** [comment] 2020-02-26 12:09
Fixed-ish, I think?

Updated to newest version and I can use the decorator.

However, it fails when trying to generate the apispec.


```
  File "/Users/nicholas/src/SocialMedia-2.0/bin/../src/sm2/common/utils/api_spec_helper.py", line 47, in generate_apispec
    API_SPEC.path(urlspec=route)
  File "/Users/nicholas/.virtualenvs/sm2py37/lib/python3.7/site-packages/apispec/core.py", line 268, in path
    path=path, operations=operations, parameters=parameters, **kwargs
  File "/Users/nicholas/.virtualenvs/sm2py37/lib/python3.7/site-packages/apispec_webframeworks/tornado.py", line 100, in path_helper
    return self.tornadopath2openapi(urlspec, params_method)
  File "/Users/nicholas/.virtualenvs/sm2py37/lib/python3.7/site-packages/apispec_webframeworks/tornado.py", line 76, in tornadopath2openapi
    path = path_tpl % params
TypeError: not all arguments converted during string formatting
```

The decorator expects us to change the method signature, but then upon changing the method signature to receive the args, that fails.

**Comment by elfjes** [comment] 2020-02-26 13:39
@nicholasamorim are you using named capture groups in your URLSpec? eg. `r"/(?P<arg>.+)/"`. The current solution only works with named capture groups.

**Comment by nicholasamorim** [comment] 2020-02-26 13:51
Right, but that's for argument defined at path-level. This specific code only has plain urls such as `/api/v1/sign`. I'm expecting args to come from the body of the request (or the querystring, potentially).


```
class MySchema(Schema):
    somefield = fields.Raw(description="The data to be signed.")


class MyHandler(RequestHandler):
    # URL: /api/v1/myhandler
    @use_kwargs(MySchema()):
    def post(self, **kwargs):
	    print(kwargs.get('somefield'))
    
```

Shouldn't the above work just fine?

**Comment by elfjes** [comment] 2020-02-26 14:23
Hmm I'm having trouble reproducing your error. The following code works fine for me:

```python
import json

from apispec import APISpec
from apispec_webframeworks.tornado import TornadoPlugin
from marshmallow import Schema, fields
from tornado.routing import URLSpec
from tornado.web import RequestHandler
from webargs.tornadoparser import use_kwargs


class MySchema(Schema):
    somefield = fields.Raw(description="The data to be signed.")


class MyHandler(RequestHandler):
    @use_kwargs(MySchema())
    def post(self, **kwargs):
        """post a thing.
        ---
        description: Post a thing
        responses:
            200:
                description: the response
        """
        print(kwargs.get('somefield'))


spec = APISpec(
    title="My API",
    version="1.0.0",
    openapi_version="3.0.2",
    plugins=[TornadoPlugin()],
)
urlspec = URLSpec("/api/v1/myhandler", MyHandler)
spec.path(urlspec=urlspec)


print(json.dumps(spec.to_dict(), indent=2))
```

Could you provide a full minimal example that reproduces the error?

**Comment by nicholasamorim** [comment] 2020-02-26 15:52
@elfjes Thanks for the snippet.

At first, I was a bit baffled because your snippet gave me the same error but I apologize. I was using `apispec-webframworks` version `0.5.0` and not `0.5.2` - with 0.5.2 the error is gone.

I updated webargs and apispec but forgot that this specific set of features is another lib.

**Comment by elfjes** [comment] 2020-02-26 16:01
Alright no worries, I'm glad it worked out for you :)
